[book]
authors = ["Emre Ergun"]
language = "en"
multilingual = false
src = "src"
title = "Web and Mobile Development Explained"

[output.html]
git-repository-url="https://github.com/emre-ergun/mdbook-webmobile"

[output.html.playground]
runnable = false